## Numpy

In [42]:
import numpy as np

In [4]:
a = np.array([[1,6],
            [2,8],
            [3,11],
            [3,10],
            [1,7]])

In [5]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

### Task 1. Mean value every column

In [10]:
mean_a = np.mean(a, axis = 0)

In [11]:
mean_a


array([2. , 8.4])

### Task 2

In [44]:
a_centered = np.subtract(a, mean_a)

In [45]:
a_centered


array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Task 3

In [46]:
a_centered_trans = a_centered.transpose()
a_centered_trans

array([[-1. ,  0. ,  1. ,  1. , -1. ],
       [-2.4, -0.4,  2.6,  1.6, -1.4]])

In [51]:
a_centered_sp = a_centered_trans[0] @ a_centered_trans[1]
a_centered_sp / (a_centered.shape[0] - 1)

2.0

### Task 4

In [43]:
np.cov(a.transpose())

array([[1. , 2. ],
       [2. , 4.3]])

# Work with Pandas

### Task 1

In [29]:
import pandas as pd

In [30]:
authors = pd.DataFrame({
    'author_id': [1, 2, 3],
    'author_name': ['Тургенев', 'Чехов', 'Островский']
})
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [33]:
books = pd.DataFrame({
    'author_id': [1, 1, 1, 2, 2, 3, 3],
    'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
    'price': [450, 300, 350, 500, 450, 370, 290]
})
books

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

### Task 2

Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.

In [34]:
author_price = pd.merge(authors, books, on='author_id', how='inner')
author_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

### Task 3

Создайте датафрейм top5, в котором содержатся строки из author_price с пятью самыми дорогими книгами.

In [35]:
top5 = author_price.nlargest(5, 'price')
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

### Task 4 
Создайте датафрейм author_stat на основе информации из authors_price. В датафрейме authors_stat должны быть четыре столбца:

author_name, min_price, max_price, mean_price, 

в которых должны содержаться сообветствнно имя автора, минимальная, максимальная и средняя цена на книги этого автора

In [36]:
author_price['price_min'] = author_price['price']
author_price['price_max'] = author_price['price']
author_price['price_mean'] = author_price['price']
author_price

author_id author_name            book_title  price  price_min  price_max  \
0          1    Тургенев           Отцы и дети    450        450        450   
1          1    Тургенев                 Рудин    300        300        300   
2          1    Тургенев     Дворянское гнездо    350        350        350   
3          2       Чехов      Толстый и тонкий    500        500        500   
4          2       Чехов       Дама с собачкой    450        450        450   
5          3  Островский                 Гроза    370        370        370   
6          3  Островский  Таланты и поклонники    290        290        290   

   price_mean  
0         450  
1         300  
2         350  
3         500  
4         450  
5         370  
6         290

In [63]:
author_stat = author_price.groupby('author_name').agg({'price_min': 'min', 'price_max': 'max', 'price_mean': 'mean'})
author_stat

price_min  price_max  price_mean
author_name                                  
Островский         290        370  330.000000
Тургенев           300        450  366.666667
Чехов              450        500  475.000000

### Task 5**

In [38]:
author_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
author_price

author_id author_name            book_title  price  price_min  price_max  \
0          1    Тургенев           Отцы и дети    450        450        450   
1          1    Тургенев                 Рудин    300        300        300   
2          1    Тургенев     Дворянское гнездо    350        350        350   
3          2       Чехов      Толстый и тонкий    500        500        500   
4          2       Чехов       Дама с собачкой    450        450        450   
5          3  Островский                 Гроза    370        370        370   
6          3  Островский  Таланты и поклонники    290        290        290   

   price_mean    cover  
0         450  твердая  
1         300   мягкая  
2         350   мягкая  
3         500  твердая  
4         450  твердая  
5         370   мягкая  
6         290   мягкая

In [40]:
?pd.pivot_table


In [46]:
book_info = pd.pivot_table(author_price, values='price', index=['author_name'], columns=['cover'], aggfunc=np.sum, fill_value = 0)
book_info

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950

In [48]:
book_info.to_pickle('book_info.pkl')

In [49]:
book_info2 = pd.read_pickle('book_info.pkl')
book_info2

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950